on:
  release:
    type: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.35
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: amd64
          project_path: ./cmd/tip-k8ctx
